name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 
        uses: actions/setup-java@v2
        with:
          java-version: '21.0.6'
          distribution: 'adoptopenjdk'


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache SonarCloud dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-sonar-

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1
      with:
        organization: chiraz-lab
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        extraArgs: '-X'
