name: Deploy to S3

on:
  push:
    branches:
      - main  # Déclenche l'action à chaque fois qu'un commit est poussé sur la branche `main`

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utilise une machine Ubuntu pour exécuter l'action

    steps:
      # Étape 1: Vérifier le code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2: Installer AWS CLI
      - name: Set up AWS CLI
        run: |
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      # Étape 3: Configurer les identifiants AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Remplacez par la région de votre bucket S3

      # Étape 4: Déployer sur S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./ s3://bucketest-chiraz/ --delete

