name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 
        uses: actions/setup-java@v4.2.0
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          organization: chiraz-lab
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          extraArgs: '-X'
